spring:
  cloud:
    gateway:

      metrics:
        enabled: true

      routes:

        - id: passenger-service
          uri: lb://PASSENGER-SERVICE
          predicates:
            - Path=/passenger/**

          filters:
            - name: CircuitBreaker
              args:
                name: passengerServiceCircuit
                fallbackUri: forward:/fallback/passenger

        - id: carrentals-service
          uri: lb://CARRENTALS-SERVICE
          predicates:
            - Path=/cars/**

          filters:
            - name: CircuitBreaker
              args:
                name: carrentalsServiceCircuit
                fallbackUri: forward:/fallback/carrentals
